### ISSUE TITLE
Buggy behavior when detaching a light bulb from the black box

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#18] opened 2016-11-09 04:37 UTC
From https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/5#issuecomment-259331415

 Something's not right here @samreid.
![light_bulb](https://cloud.githubusercontent.com/assets/8419308/20127189/9d48abb4-a5f9-11e6-858e-e54af9af8646.gif)

**Comment by samreid** [comment] 2016-11-09 04:50
The same problem does not appear for resistors or batteries, or for the light bulb's other terminal.  If the mouse is not over the light bulb when releasing, then the behavior is correct.  So there is some listener getting an event when over the light bulb that is interfering.

**Comment by samreid** [comment] 2016-11-09 05:00
If I click on the cut button outside of the light bulb region, it shows as depressed.  If I click on the cut button where it overlays the light bulb region, it does not show as depressed.  Somehow the light bulb instead of the cut button is getting the event, even though the cut button is in front.

**Comment by samreid** [comment] 2016-11-09 05:09
This problem is not new, it is also present in the last version we delivered to Shima:

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.0-dev.23/circuit-construction-kit-black-box-study_en.html

**Comment by samreid** [comment] 2016-11-09 05:20
If I setPickable: false on CCKLightBulbForegroundNode then the problem disappears.  What is CCKLightBulbForegroundNode?  Will setPickable on it cause other problems?

**Comment by samreid** [comment] 2016-11-09 05:25
Here's the issue that introduced the foreground: https://github.com/phetsims/circuit-construction-kit-common/issues/188 

Apparently it is for showing the electrons in the correct z-order

**Comment by samreid** [comment] 2016-11-09 05:30
In the above commit, the bulb foreground was set to be not pickable, so the behavior in the issue description no longer happens.  However, if clicking on the black box node and then another part of the light bulb, it still shows the same buggy behavior.

**Comment by samreid** [comment] 2016-11-09 17:00
The simplest way to reproduce the problem:

1. Go to 2nd screen
2. Attach bulb to black box
3. Drag other vertex

**Comment by samreid** [comment] 2016-11-09 18:38
Fixed above, will be ready for review in next version.

**Comment by arouinfar** [comment] 2016-11-09 20:56
Unable to reproduce in 1.0.4-rc.2. Closing!

**Closed by arouinfar** 2016-11-09 20:56 UTC
Labels: priority:2-high, status:fixed-pending-testing
