### ISSUE TITLE
Solder should be rendered properly on startup

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#36] opened 2017-01-25 16:26 UTC
From https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/31

@kathy-phet said:

> only comment I have is it would be incrementally improved if the solder joints were layered on top ... right now they seem to be below the special stubs. But certainly could leave as it is.

and

> noticed solder joints do show up nicely on joints after pressing reset all ... if they could start with that look it seems like it would be better.

@arouinfar said:

> I haven't found any issues with 1.0.8-dev.3, aside from the solder joint issue that @kathy-phet described.

This should be implemented for the 1.0.8 branch and for master.

**Comment by samreid** [comment] 2017-01-25 17:24
In the preceding commit, I added a workaround for showing the solder in the correct order.  It is published here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.8-dev.4/circuit-construction-kit-black-box-study_en.html

I spent nearly an hour investigating the "right way" to do this, but given the current implementation it would have been very convoluted, so I resorted to this 2-line workaround which seems to behave nicely.

The workaround is to reset the model and view on startup, which may have (but hopefully does not) have unintended consequences.

@arouinfar and @kathy-phet would you like to review this version?  Should @phet-steele dev test it?  After this, should we move forward with an RC and more elaborate testing?  I'll still need to publish the PhET brand of this, the current dev version is the PhET brand.

**Comment by arouinfar** [comment] 2017-01-26 17:22
@samreid the workaround seems to be working fine. I can do a bit more testing on 1.0.8-dev.4, but I think we'll want to wait for the fire artwork (https://github.com/phetsims/circuit-construction-kit-common/issues/72) and hiding the reveal button (https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/37) before doing more elaborate testing or getting @phet-steele on board.

**Comment by arouinfar** [comment] 2017-01-26 17:24
Tagging for #32.

**Comment by samreid** [comment] 2017-01-26 17:27
@arouinfar can this issue be closed?

**Comment by arouinfar** [comment] 2017-01-26 17:28
I'll go ahead and close this issue, and open new issues if I find anything else in 1.0.8-dev.4.

**Comment by arouinfar** [comment] 2017-02-03 18:10
In 1.0.8-dev.9, I noticed that the solder joint can become transparent if you
* Go to Black Box on startup. Solder joint looks fine.
* Switch to Test, and then back to Explore.
* Solder joint is now transparent and remains transparent, even when components are attached.
![image](https://cloud.githubusercontent.com/assets/8419308/22602558/fc005436-ea00-11e6-96bb-21929213201f.png)

I retested 1.0.8-dev.4, and the issue is also present there.

**Comment by samreid** [comment] 2017-02-08 15:59
I moved the preceding comment to a new issue, closing.

**Comment by samreid** [comment] 2017-02-10 20:23
Reopening for phetsims/tasks#781 but as pointed out in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/46 we will need a better solution.

**Comment by samreid** [comment] 2017-02-10 21:04
Proposed fix is above.  Fairly significant change, may have disturbed some other aspect of layering.   I may need to redo the entire layering subsystem before this is published on our website.  But maybe this will be good enough for RC.3.

**Comment by samreid** [comment] 2017-02-15 18:44
In rc.3 it looks like this on startup or reset:

![image](https://cloud.githubusercontent.com/assets/679486/22989685/0d03bb66-f374-11e6-90d8-2a91e3a89198.png)

When attaching a wire to the black box vertex, I see this:

![image](https://cloud.githubusercontent.com/assets/679486/22989699/1c757012-f374-11e6-8fbc-5b40f50ed2d1.png)

Unexpected and not ideal, but it doesn't seem like a showstopper for sharing.

**Comment by phet-steele** [comment] 2017-02-15 18:55
@samreid, in rc.3 anything attached to the BB will be layered above the BB at first, but then be layered under it when switching to and back from another challenge.

Before switch:
<img width="675" alt="screen shot 2017-02-15 at 11 53 28 am" src="https://cloud.githubusercontent.com/assets/5863899/22990171/8c01c4c0-f375-11e6-8736-2900724fdd93.png">

After switch:
<img width="646" alt="screen shot 2017-02-15 at 11 53 37 am" src="https://cloud.githubusercontent.com/assets/5863899/22990182/9520e2ca-f375-11e6-8059-55fd0d8a3c88.png">

**Comment by phet-steele** [comment] 2017-02-15 18:58
Going to move the above comment to a new issue.

**Comment by phet-steele** [comment] 2017-02-16 20:03
https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/36#issuecomment-280100528 also occurs when toggling play/pause (with nothing attached).

**Comment by samreid** [comment] 2017-02-17 05:35
@arouinfar is the behavior in rc.3 acceptable for our February deadline?

**Comment by kathy-phet** [comment] 2017-02-17 18:16
Sam - The layering issue shown in r3 where the circuit elements end up behind the black box seems problematic for an actual classroom use.

**Comment by arouinfar** [comment] 2017-02-17 18:18
@kathy-phet that particular layering issue is not present in rc.4.

**Comment by kathy-phet** [comment] 2017-02-17 18:22
Oh - I see I thought Sam was talking about rc.3. I see now its rc.4.

**Comment by arouinfar** [comment] 2017-02-17 18:33
@samreid I haven't found any issues with the solder rendering on startup, or the re-layering described in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/36#issuecomment-280100528 in rc.4.

**Closed by arouinfar** 2017-02-17 18:33 UTC
Labels: priority:2-high, status:fixed-pending-testing
