### ISSUE TITLE
Disable connection to other end of stub in "test circuit"

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/circuit-construction-kit-black-box-study#38] opened 2017-01-26 20:22 UTC
@samreid - As shown below it looks like the latest version for Shima allows connection to either end of the "stubs" when building inside the black box. I thought it would have automatically disallowed connection to the end outside of the black box given its definition as part of the external circuit. 

![image](https://cloud.githubusercontent.com/assets/5096804/22348826/664a1f08-e3ca-11e6-9d7b-ce02d15189e2.png)

**Comment by samreid** [comment] 2017-01-27 17:06
Oops, I noticed this change makes it possible to move the stub wires:

![image](https://cloud.githubusercontent.com/assets/679486/22379838/4ccab67e-e478-11e6-810b-6f621577e3fb.png)

**Comment by samreid** [comment] 2017-01-27 17:21
I added a new flag that tracks the outer wire stubs.  It seems to be working OK with the caveat that it is not possible to rotate a fixed length circuit element (such as a battery) attached to an outer wire stub vertex.  Still, that may be ok.  I'll publish a version for @kathy-phet and @arouinfar to investigate.

**Comment by samreid** [comment] 2017-01-27 17:27
Dev version published here.  @kathy-phet and @arouinfar can you please test this fix?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.8-dev.6/circuit-construction-kit-black-box-study_en.html

**Comment by samreid** [comment] 2017-01-27 19:37
@kathy-phet and I discussed this on Zoom today and realized that the proposed fix in dev.6 has the undesirable behavior that cutting the wire stub outer vertex deletes it.  We hypothesize this was being handled by the "blackBoxInterface" property.  So we would like to go back to 1.0.8-dev.4, so leaving the outer vertex marked as black box interface, but make them unattachable when in test mode.

If that doesn't work easily, then perhaps we can investigate bumping the wires inside before the attachment algorithm runs (though the attachments happen during drag, so that may be impossible).

**Comment by samreid** [comment] 2017-01-27 20:13
In the above commits, I restored the outer wire stub to being a black box interface vertex, which handles connections, adjacent rotations and disconnections properly.  Then I added code which prevents attachment when in the "test" mode.  Brief tests seem OK, I'll share a link for @kathy-phet and @arouinfar to test.  If all seems well, I'll move this fix to master.

**Comment by samreid** [comment] 2017-01-27 20:16
@kathy-phet and @arouinfar can you please test this version with the fixes for the wire stubs?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.8-dev.7/circuit-construction-kit-black-box-study_en.html

**Comment by samreid** [comment] 2017-01-27 21:15
I went ahead and pushed this same fix to master.

**Comment by arouinfar** [comment] 2017-02-02 17:30
Looks good @samreid. I haven't been able to reproduce the issues.

**Closed by arouinfar** 2017-02-02 17:30 UTC
Labels: priority:2-high
